# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest
parameters:
- name: 'prd_app'
  values: 
     - ApplicatioN-PRD-APP1
     - ApplicatioN-PRD-APP2
     - ApplicatioN-PRD-APP3
     - ApplicatioN-PRD-APP4
- name: ServersList
  type: object
  default:
     - ApplicatioN-PRD-APP1
     - ApplicatioN-PRD-APP2   
stages:
  - stage: Test
    displayName: Test
    condition: always()
    jobs:
      - job: Test_Job
        displayName: 'Test_Job_Display'
      - deployment: Deployment_Test_Job
        environment:
         name: ${{ parameters.prd_app }}
         resourceType: VirtualMachine
        strategy:
         runOnce:
           deploy:
            steps:
              - powershell: write-host "Hello world"+$env:COMPUTERNAME
              - powershell: start-sleep 5
              - ${{ each serv in parameters.ServersList }}:
                 - script: ping ${{ serv }} -n 1
