# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#---------[Pipeline for Restart Application on Pre Prod servers!]
trigger: none

pool:
  vmImage: ubuntu-latest
#   
parameters:
- name: 'pprd_app_stop'
  values: 
     - Name-pprd-app1
     - Name-pprd-app2
     - Name-pprd-app3
     - Name-pprd-app4
- name: 'pprd_app_start'
  values: 
     - Name-pprd-app1
     - Name-pprd-app2
     - Name-pprd-app3
     - Name-pprd-app4


#Stage 1 - shutting-down nameof-app
stages:
  - stage: Stop_Jboss_Server
    displayName: Stop_Jboss_Server
    #condition: always()
    jobs:
      - job: Stop_JBoss
        displayName: Stop_Jboss
      - deployment: 'Stop_Jboss_Server'
        environment:
         name: ${{ parameters.pprd_app_stop }}
         resourceType: VirtualMachine
        strategy:
         runOnce:
           deploy:
            steps:
              - script: net stop nameof-app
              - powershell: Start-Sleep -Seconds 90
#Stage 2 - start the jboss-9001
  - stage: Start_Jboss
    displayName: 'Start_Jboss'
    #condition: always()
    jobs:
      - job: Start_JBosss
        displayName: Start_Jboss
      - deployment: 'Start_Jboss_Server'
        environment:
         name: ${{ parameters.pprd_app_start }}
         resourceType: VirtualMachine
        strategy:
         runOnce:
           deploy:
            steps:             
              - script: net start nameof-app

# Jboss-9001 name of the application inside the VM.
